name: Build and Push Node22 Container

on:
  push:
    branches: [ "main" ]

# Força o executor do GitHub a usar o Node.js 24 para as Actions
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # A v4 é compatível, mas o ambiente precisa do Node 24

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          # Isso garante que o nome do usuário fique em minúsculo
          USER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          
          # Vamos usar um nome de imagem mais simples e direto
          IMAGE_NAME="ghcr.io/$USER_LOWER/backend-node22:latest"
          
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME